credentials:
  aws:
    AWS_ACCESS_KEY_ID: # UNCOMMENT & FILL IN HERE
    AWS_SECRET_ACCESS_KEY: # UNCOMMENT & FILL IN HERE
    AWS_DEFAULT_REGION: # UNCOMMENT & FILL IN HERE
    AWS_SSH_KEY_NAME: # UNCOMMENT & FILL IN HERE
  ##########
  # TODO:
  ##########
  # gcp:
  #  GCP_ACCESS_KEY_ID: # UNCOMMENT & FILL IN HERE
  #  ...
  # azure:
  #  AZURE_ACCESS_KEY_ID: # UNCOMMENT & FILL IN HERE
